### ISSUE TITLE
JS markup error in Opera

### ISSUE THREAD

**Issue by Playon24** [TrinityCore/aowow#13]
Just found out that all categories of the `All About AoWoW` and `Goodies` tabs do not display in Opera browser because of this error:
![markuperror_opera](https://cloud.githubusercontent.com/assets/652531/25786526/8a81b686-339f-11e7-834d-ebbf869fd770.JPG)

**Comment by Sarjuuk** [comment]
hmpf .. time to get a chrome based browser i guess...

**Comment by Sarjuuk** [comment]
works for me in Opera 44. Also my javascript isn't minified. Did you minify yours? If so, that *could* break the javacript.

**Comment by Playon24** [comment]
Nope i didnt minify any js.
But your FAQ tab dose not dsplay any text either.

**Comment by Aokromes** [comment]
maybe faq don't have content? :)

**Comment by Sarjuuk** [comment]
It has some placeholder text.

And it doesn't show in my screenshot because i halted script execution, so you can see in the inspector, that there is a valid Markup-Object that can can be called with .toHtml().

There are apache_modules that try to optimize such things by themselves. Maybe have another look at your modules^^

**Comment by Playon24** [comment]
Sorry for this.
It is a CloudFlare problem, the Auto Minify option that i had enabled was the cause. I have deactivated the poxying and the page works just fine in Opera.

As future refrence you can also write in the readme that CloudFlare could cause display problems if some certian options are enabled.

**Comment by Sarjuuk** [comment]
another one for the Q/A-section^^
